text = """
I am applying to the MSc Statistics (Data Science and Machine Learning) at Imperial College London to deepen my understanding of high-dimensional data analysis and to develop the practical skills needed for a career in quantitative research. Throughout my academic journey and industrial experience in finance, I have become increasingly aware of the inevitability of uncertainty. That has naturally drawn me to statistics, as it offers a structured, mathematically rigorous way to deal with this randomness. Transitioning from deterministic to probabilistic reasoning has transformed how I think and is my primary motivation to study statistics further.
I am currently completing my fourth and final year of a BSc in Economics and Finance at University College Dublin, specialising in Mathematics and Statistics. I have found the most rewarding parts of my degree have been the mathematically rigorous modules, including Linear Algebra, Statistical Modelling, Advanced Calculus, Stochastic Models and Time Series. Together, these modules have given me a strong foundation in mathematics and programming that I am keen to develop further at Imperial, particularly through the Fundamentals of Statistical Inference and the Computational Statistics and Machine Learning modules.
That foundation became especially relevant during my year-long industrial placement at Abbey Capital, where I worked in a research role within the managed futures firm. Using Python and Excel, I applied statistical methods to large, dynamic time-series datasets, evaluating performance and risk at the fund, strategy, and asset levels, focusing on risk-adjusted performance, downside risk, drawdown behaviour and diversification effects. I also modelled realised volatility across distinct regimes to support target-volatility recommendations for allocation and risk discussions. This experience illustrated to me the possibilities and impact of statistical thinking and continues to motivate me to pursue a research-oriented career. 
Inspired by the utility of statistics in work and college, I decided to explore ways of incorporating it into my personal life. While training for a marathon, strength training, and playing football for UCD, I realised the need for better training and recovery. I decided to create a Python system to automatically collect, clean and visualise my training data, dynamically updating my training plan to improve my performance and reduce my injury risk. Working with noisy, non-stationary data, both in this project and in industry, forced me to revise my foundations, to ensure that my assumptions and interpretations were rigorously defensible. This journey brought me back to first principles, where I revisited epistemology through Hume’s “An Enquiry Concerning Human Understanding” and Ayer’s “Language, Truth and Logic” to understand the limits of empirical induction and strengthened my intuition of mathematical foundations through some of Halmos and Kolmogorov’s works on set theory and probability. 
Imperial is my first choice because the Data Science and Machine Learning stream combines the statistical rigour and modern application I’m looking for. The core modules, particularly Applied Statistics and Computational Statistics, cover the key areas I want to strengthen. The electives also really appeal to me; I’m especially drawn to Deep Learning and Statistical Finance. I’m also excited by the opportunity to apply the training to a real problem with the research project, inspired by the Time Series and Statistics in Finance research groups, whose work on volatility modelling and stochastic processes directly addresses the problems and complexities I encountered in industry. Ultimately, I believe studying at Imperial would be the best way for me to prepare for my career, and I would be excited and grateful for the opportunity to learn from and contribute to its statistics community.
"""

print(len(text))                      # characters (includes newlines)
print(len(text.replace("\n", "")))    # characters (excluding newlines)
print(len(text.split()))   